### ISSUE TITLE
 我最近也在学习，能请教个问题吗

### ISSUE THREAD

**Issue by XLloyd** [yyq-3/InjectDLL#1]

**Comment by yyq-3** [comment]
你描述一下问题

**Comment by XLloyd** [comment]
> 你描述一下问题

我按照一些教程和参考您的这个方法，最后注入的时候，dll弹窗并没有出来，是不是已经被屏蔽了

**Comment by yyq-3** [comment]
> > 你描述一下问题
> 
> 我按照一些教程和参考您的这个方法，最后注入的时候，dll弹窗并没有出来，是不是已经被屏蔽了

你可以通过一些进程查看工具来看一下是否已经将dll成功注入，另外我看了一下现在仓库的代码，我后来的改动发现似乎没有提交，现在拖拽的方式有问题，与管理员权限有关

**Comment by XLloyd** [comment]
> 你可以通过一些进程查看工具来看一下是否已经将dll成功注入，另外我看了一下现在仓库的代码，我后来的改动发现似乎没有提交，现在拖拽的方式有问题，与管理员权限有关

谢谢，我把dll注入到别的进程里，弹窗就可以出来。通过写入dll地址在进程内存地址查看，确实写入了
